using System;
using Volo.Abp.Domain.Services;
using Volo.Abp.Domain.Repositories;

namespace DemoTuan5.Countries
{
    public class CountryManager : CountryManagerBase
    {
        //<suite-custom-code-autogenerated>
        public CountryManager(ICountryRepository countryRepository)
            : base(countryRepository)
        {
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}