using System;
using System.Linq;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using Volo.Abp.Domain.Entities;
using Volo.Abp.Domain.Entities.Auditing;
using Volo.Abp.MultiTenancy;
using JetBrains.Annotations;
using Volo.Abp.Domain.Entities;

using Volo.Abp;

namespace DemoTuan5.Countries
{
    public class Country : CountryBase
    {
        //<suite-custom-code-autogenerated>
        protected Country()
        {

        }

        public Country(Guid id, string? code = null, string? description = null)
            : base(id, code, description)
        {
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}