using System;
using Volo.Abp.Domain.Services;
using Volo.Abp.Domain.Repositories;

namespace DemoTuan5.WarehouseLocations
{
    public class WarehouseLocationManager : WarehouseLocationManagerBase
    {
        //<suite-custom-code-autogenerated>
        public WarehouseLocationManager(IWarehouseLocationRepository warehouseLocationRepository)
            : base(warehouseLocationRepository)
        {
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}