using DemoTuan5.Countries;
using DemoTuan5.Warehouses;
using System;
using System.Linq;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using Volo.Abp.Domain.Entities;
using Volo.Abp.Domain.Entities.Auditing;
using Volo.Abp.MultiTenancy;
using JetBrains.Annotations;

using Volo.Abp;

namespace DemoTuan5.WarehouseLocations
{
    public class WarehouseLocation : WarehouseLocationBase
    {
        //<suite-custom-code-autogenerated>
        protected WarehouseLocation()
        {

        }

        public WarehouseLocation(Guid id, Guid? countryId, Guid? warehouseId, string code, bool active, int idx, string? description = null)
            : base(id, countryId, warehouseId, code, active, idx, description)
        {
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}