using System;
using System.IO;
using System.Linq;
using System.Collections.Generic;
using System.Threading.Tasks;
using System.Linq.Dynamic.Core;
using Microsoft.AspNetCore.Authorization;
using Volo.Abp;
using Volo.Abp.Application.Dtos;
using Volo.Abp.Application.Services;
using Volo.Abp.Domain.Repositories;
using DemoTuan5.Permissions;
using DemoTuan5.Countries;
using MiniExcelLibs;
using Volo.Abp.Content;
using Volo.Abp.Authorization;
using Volo.Abp.Caching;
using Microsoft.Extensions.Caching.Distributed;
using DemoTuan5.Shared;

namespace DemoTuan5.Countries
{
    public class CountriesAppService : CountriesAppServiceBase, ICountriesAppService
    {
        //<suite-custom-code-autogenerated>
        public CountriesAppService(ICountryRepository countryRepository, CountryManager countryManager, IDistributedCache<CountryExcelDownloadTokenCacheItem, string> excelDownloadTokenCache)
            : base(countryRepository, countryManager, excelDownloadTokenCache)
        {
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}