using System;
using Volo.Abp.Domain.Services;
using Volo.Abp.Domain.Repositories;

namespace DemoTuan5.Warehouses
{
    public class WarehouseManager : WarehouseManagerBase
    {
        //<suite-custom-code-autogenerated>
        public WarehouseManager(IWarehouseRepository warehouseRepository)
            : base(warehouseRepository)
        {
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}