using System;
using System.Linq;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using Volo.Abp.Domain.Entities;
using Volo.Abp.Domain.Entities.Auditing;
using Volo.Abp.MultiTenancy;
using JetBrains.Annotations;
using Volo.Abp.Domain.Entities;

using Volo.Abp;

namespace DemoTuan5.Warehouses
{
    public class Warehouse : WarehouseBase
    {
        //<suite-custom-code-autogenerated>
        protected Warehouse()
        {

        }

        public Warehouse(Guid id, bool active, string? code = null, string? description = null)
            : base(id, active, code, description)
        {
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}